# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Documents\maya\code\Cadence\resources\gui\GaitGeneratorUI.ui'
#
# Created: Mon Aug 27 09:09:25 2012
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 286)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.strideLengthSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.strideLengthSlider.setMaximum(200)
        self.strideLengthSlider.setSingleStep(10)
        self.strideLengthSlider.setProperty("value", 100)
        self.strideLengthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.strideLengthSlider.setObjectName("strideLengthSlider")
        self.verticalLayout.addWidget(self.strideLengthSlider)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gaitPhaseSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.gaitPhaseSlider.setMinimum(-90)
        self.gaitPhaseSlider.setMaximum(90)
        self.gaitPhaseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gaitPhaseSlider.setObjectName("gaitPhaseSlider")
        self.verticalLayout.addWidget(self.gaitPhaseSlider)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.dutyFactorHindSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.dutyFactorHindSlider.setMinimum(10)
        self.dutyFactorHindSlider.setMaximum(90)
        self.dutyFactorHindSlider.setProperty("value", 50)
        self.dutyFactorHindSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dutyFactorHindSlider.setObjectName("dutyFactorHindSlider")
        self.verticalLayout.addWidget(self.dutyFactorHindSlider)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.dutyFactorForeSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.dutyFactorForeSlider.setMinimum(10)
        self.dutyFactorForeSlider.setMaximum(90)
        self.dutyFactorForeSlider.setProperty("value", 50)
        self.dutyFactorForeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dutyFactorForeSlider.setObjectName("dutyFactorForeSlider")
        self.verticalLayout.addWidget(self.dutyFactorForeSlider)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.cyclesSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.cyclesSlider.setMinimum(1)
        self.cyclesSlider.setMaximum(20)
        self.cyclesSlider.setProperty("value", 10)
        self.cyclesSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cyclesSlider.setObjectName("cyclesSlider")
        self.verticalLayout.addWidget(self.cyclesSlider)
        self.runButton = QtGui.QPushButton(Form)
        self.runButton.setGeometry(QtCore.QRect(420, 250, 131, 23))
        self.runButton.setObjectName("runButton")
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 10, 91, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.strideLengthLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.strideLengthLabel.setFont(font)
        self.strideLengthLabel.setObjectName("strideLengthLabel")
        self.verticalLayout_2.addWidget(self.strideLengthLabel)
        self.gaitPhaseLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gaitPhaseLabel.setFont(font)
        self.gaitPhaseLabel.setObjectName("gaitPhaseLabel")
        self.verticalLayout_2.addWidget(self.gaitPhaseLabel)
        self.dutyFactorHindLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dutyFactorHindLabel.setFont(font)
        self.dutyFactorHindLabel.setObjectName("dutyFactorHindLabel")
        self.verticalLayout_2.addWidget(self.dutyFactorHindLabel)
        self.dutyFactorForeLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dutyFactorForeLabel.setFont(font)
        self.dutyFactorForeLabel.setObjectName("dutyFactorForeLabel")
        self.verticalLayout_2.addWidget(self.dutyFactorForeLabel)
        self.cyclesLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cyclesLabel.setFont(font)
        self.cyclesLabel.setObjectName("cyclesLabel")
        self.verticalLayout_2.addWidget(self.cyclesLabel)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.strideLengthSlider, QtCore.SIGNAL("valueChanged(int)"), self.strideLengthLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Stride Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Gait Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Duty Factor (Hind)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Duty Factor (Fore)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("Form", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.strideLengthLabel.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.gaitPhaseLabel.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.dutyFactorHindLabel.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.dutyFactorForeLabel.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.cyclesLabel.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

