# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/scott/Python/Cadence/resources/widget/tools/TrackwayIoWidget/TrackwayIoWidget.ui'
#
# Created: Mon Feb 17 16:18:19 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class PySideUiFileSetup(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 581)
        Form.horizontalLayout_5 = QtGui.QHBoxLayout(Form)
        Form.horizontalLayout_5.setSpacing(0)
        Form.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_5.setObjectName("horizontalLayout_5")
        Form.widget_8 = QtGui.QWidget(Form)
        Form.widget_8.setObjectName("widget_8")
        Form.verticalLayout_6 = QtGui.QVBoxLayout(Form.widget_8)
        Form.verticalLayout_6.setSpacing(0)
        Form.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_6.setObjectName("verticalLayout_6")
        Form.widget_9 = QtGui.QWidget(Form.widget_8)
        Form.widget_9.setObjectName("widget_9")
        Form.verticalLayout = QtGui.QVBoxLayout(Form.widget_9)
        Form.verticalLayout.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout.setObjectName("verticalLayout")
        Form.label_3 = QtGui.QLabel(Form.widget_9)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.label_3.setFont(font)
        Form.label_3.setObjectName("label_3")
        Form.verticalLayout.addWidget(Form.label_3)
        Form.label_7 = QtGui.QLabel(Form.widget_9)
        Form.label_7.setObjectName("label_7")
        Form.verticalLayout.addWidget(Form.label_7)
        Form.widget_3 = QtGui.QWidget(Form.widget_9)
        Form.widget_3.setObjectName("widget_3")
        Form.horizontalLayout_3 = QtGui.QHBoxLayout(Form.widget_3)
        Form.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_3.setObjectName("horizontalLayout_3")
        Form.pushButton = QtGui.QPushButton(Form.widget_3)
        Form.pushButton.setObjectName("pushButton")
        Form.horizontalLayout_3.addWidget(Form.pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_3.addItem(spacerItem)
        Form.verticalLayout.addWidget(Form.widget_3)
        Form.verticalLayout_6.addWidget(Form.widget_9)
        Form.line_2 = QtGui.QFrame(Form.widget_8)
        Form.line_2.setFrameShape(QtGui.QFrame.HLine)
        Form.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        Form.line_2.setObjectName("line_2")
        Form.verticalLayout_6.addWidget(Form.line_2)
        Form.widget_10 = QtGui.QWidget(Form.widget_8)
        Form.widget_10.setObjectName("widget_10")
        Form.verticalLayout_2 = QtGui.QVBoxLayout(Form.widget_10)
        Form.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_2.setObjectName("verticalLayout_2")
        Form.label_2 = QtGui.QLabel(Form.widget_10)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.label_2.setFont(font)
        Form.label_2.setObjectName("label_2")
        Form.verticalLayout_2.addWidget(Form.label_2)
        Form.label_8 = QtGui.QLabel(Form.widget_10)
        Form.label_8.setObjectName("label_8")
        Form.verticalLayout_2.addWidget(Form.label_8)
        Form.widget_2 = QtGui.QWidget(Form.widget_10)
        Form.widget_2.setObjectName("widget_2")
        Form.horizontalLayout_2 = QtGui.QHBoxLayout(Form.widget_2)
        Form.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_2.setObjectName("horizontalLayout_2")
        Form.loadAllBtn = QtGui.QPushButton(Form.widget_2)
        Form.loadAllBtn.setObjectName("loadAllBtn")
        Form.horizontalLayout_2.addWidget(Form.loadAllBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_2.addItem(spacerItem1)
        Form.verticalLayout_2.addWidget(Form.widget_2)
        Form.verticalLayout_6.addWidget(Form.widget_10)
        spacerItem2 = QtGui.QSpacerItem(20, 350, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_6.addItem(spacerItem2)
        Form.horizontalLayout_5.addWidget(Form.widget_8)
        Form.line_3 = QtGui.QFrame(Form)
        Form.line_3.setFrameShape(QtGui.QFrame.VLine)
        Form.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        Form.line_3.setObjectName("line_3")
        Form.horizontalLayout_5.addWidget(Form.line_3)
        Form.widget_7 = QtGui.QWidget(Form)
        Form.widget_7.setObjectName("widget_7")
        Form.verticalLayout_5 = QtGui.QVBoxLayout(Form.widget_7)
        Form.verticalLayout_5.setSpacing(0)
        Form.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_5.setObjectName("verticalLayout_5")
        Form.widget_4 = QtGui.QWidget(Form.widget_7)
        Form.widget_4.setObjectName("widget_4")
        Form.verticalLayout_4 = QtGui.QVBoxLayout(Form.widget_4)
        Form.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_4.setObjectName("verticalLayout_4")
        Form.label = QtGui.QLabel(Form.widget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.label.setFont(font)
        Form.label.setObjectName("label")
        Form.verticalLayout_4.addWidget(Form.label)
        Form.label_4 = QtGui.QLabel(Form.widget_4)
        Form.label_4.setObjectName("label_4")
        Form.verticalLayout_4.addWidget(Form.label_4)
        Form.widget = QtGui.QWidget(Form.widget_4)
        Form.widget.setObjectName("widget")
        Form.horizontalLayout = QtGui.QHBoxLayout(Form.widget)
        Form.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout.setObjectName("horizontalLayout")
        Form.importBtn = QtGui.QPushButton(Form.widget)
        Form.importBtn.setObjectName("importBtn")
        Form.horizontalLayout.addWidget(Form.importBtn)
        Form.overwriteImportChk = QtGui.QCheckBox(Form.widget)
        Form.overwriteImportChk.setObjectName("overwriteImportChk")
        Form.horizontalLayout.addWidget(Form.overwriteImportChk)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout.addItem(spacerItem3)
        Form.verticalLayout_4.addWidget(Form.widget)
        Form.verticalLayout_5.addWidget(Form.widget_4)
        Form.line = QtGui.QFrame(Form.widget_7)
        Form.line.setFrameShape(QtGui.QFrame.HLine)
        Form.line.setFrameShadow(QtGui.QFrame.Sunken)
        Form.line.setObjectName("line")
        Form.verticalLayout_5.addWidget(Form.line)
        Form.widget_5 = QtGui.QWidget(Form.widget_7)
        Form.widget_5.setObjectName("widget_5")
        Form.verticalLayout_3 = QtGui.QVBoxLayout(Form.widget_5)
        Form.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_3.setObjectName("verticalLayout_3")
        Form.label_5 = QtGui.QLabel(Form.widget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        Form.label_5.setFont(font)
        Form.label_5.setObjectName("label_5")
        Form.verticalLayout_3.addWidget(Form.label_5)
        Form.label_6 = QtGui.QLabel(Form.widget_5)
        Form.label_6.setObjectName("label_6")
        Form.verticalLayout_3.addWidget(Form.label_6)
        Form.widget_6 = QtGui.QWidget(Form.widget_5)
        Form.widget_6.setObjectName("widget_6")
        Form.horizontalLayout_4 = QtGui.QHBoxLayout(Form.widget_6)
        Form.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_4.setObjectName("horizontalLayout_4")
        Form.exportBtn = QtGui.QPushButton(Form.widget_6)
        Form.exportBtn.setObjectName("exportBtn")
        Form.horizontalLayout_4.addWidget(Form.exportBtn)
        spacerItem4 = QtGui.QSpacerItem(231, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_4.addItem(spacerItem4)
        Form.verticalLayout_3.addWidget(Form.widget_6)
        Form.verticalLayout_5.addWidget(Form.widget_5)
        spacerItem5 = QtGui.QSpacerItem(20, 46, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_5.addItem(spacerItem5)
        Form.horizontalLayout_5.addWidget(Form.widget_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_3.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_7.setText(QtGui.QApplication.translate("Form", "Save Maya Changes to Database", None, QtGui.QApplication.UnicodeUTF8))
        Form.pushButton.setText(QtGui.QApplication.translate("Form", "Save Selected", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_2.setText(QtGui.QApplication.translate("Form", "Load", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_8.setText(QtGui.QApplication.translate("Form", "Load Database into Maya", None, QtGui.QApplication.UnicodeUTF8))
        Form.loadAllBtn.setText(QtGui.QApplication.translate("Form", "Load All", None, QtGui.QApplication.UnicodeUTF8))
        Form.label.setText(QtGui.QApplication.translate("Form", "Import", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_4.setText(QtGui.QApplication.translate("Form", "Load CSV Spreadsheet Data Into Database", None, QtGui.QApplication.UnicodeUTF8))
        Form.importBtn.setText(QtGui.QApplication.translate("Form", "Import", None, QtGui.QApplication.UnicodeUTF8))
        Form.overwriteImportChk.setText(QtGui.QApplication.translate("Form", "Overwrite Existing", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_5.setText(QtGui.QApplication.translate("Form", "Export", None, QtGui.QApplication.UnicodeUTF8))
        Form.label_6.setText(QtGui.QApplication.translate("Form", "Write Database Data to Spreadsheet", None, QtGui.QApplication.UnicodeUTF8))
        Form.exportBtn.setText(QtGui.QApplication.translate("Form", "Export", None, QtGui.QApplication.UnicodeUTF8))

