# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/scott/Python/Cadence/resources/widget/tools/TrackwayManagerWidget/TrackwayManagerWidget.ui'
#
# Created: Mon Feb 17 16:18:19 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class PySideUiFileSetup(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(1335, 699)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setCursor(QtCore.Qt.ArrowCursor)
        Form.setAcceptDrops(False)
        Form.verticalLayout_12 = QtGui.QVBoxLayout(Form)
        Form.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_12.setObjectName("verticalLayout_12")
        Form.topBannerWidget = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.topBannerWidget.sizePolicy().hasHeightForWidth())
        Form.topBannerWidget.setSizePolicy(sizePolicy)
        Form.topBannerWidget.setObjectName("topBannerWidget")
        Form.verticalLayout_14 = QtGui.QVBoxLayout(Form.topBannerWidget)
        Form.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_14.setObjectName("verticalLayout_14")
        Form.trackwayBannerWidget = QtGui.QWidget(Form.topBannerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackwayBannerWidget.sizePolicy().hasHeightForWidth())
        Form.trackwayBannerWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.trackwayBannerWidget.setFont(font)
        Form.trackwayBannerWidget.setObjectName("trackwayBannerWidget")
        Form.horizontalLayout_4 = QtGui.QHBoxLayout(Form.trackwayBannerWidget)
        Form.horizontalLayout_4.setSpacing(0)
        Form.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        Form.horizontalLayout_4.setObjectName("horizontalLayout_4")
        Form.widget = QtGui.QWidget(Form.trackwayBannerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget.sizePolicy().hasHeightForWidth())
        Form.widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget.setFont(font)
        Form.widget.setObjectName("widget")
        Form.communityVL = QtGui.QVBoxLayout(Form.widget)
        Form.communityVL.setSpacing(0)
        Form.communityVL.setContentsMargins(0, 0, 0, 0)
        Form.communityVL.setContentsMargins(0, 0, 0, 0)
        Form.communityVL.setObjectName("communityVL")
        Form.communityLE = QtGui.QLineEdit(Form.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.communityLE.sizePolicy().hasHeightForWidth())
        Form.communityLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.communityLE.setFont(font)
        Form.communityLE.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.communityLE.setFrame(False)
        Form.communityLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.communityLE.setObjectName("communityLE")
        Form.communityVL.addWidget(Form.communityLE)
        Form.communityLbl = QtGui.QLabel(Form.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.communityLbl.sizePolicy().hasHeightForWidth())
        Form.communityLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.communityLbl.setFont(font)
        Form.communityLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.communityLbl.setObjectName("communityLbl")
        Form.communityVL.addWidget(Form.communityLbl)
        Form.horizontalLayout_4.addWidget(Form.widget)
        Form.widget1 = QtGui.QWidget(Form.trackwayBannerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget1.sizePolicy().hasHeightForWidth())
        Form.widget1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget1.setFont(font)
        Form.widget1.setObjectName("widget1")
        Form.siteVL = QtGui.QVBoxLayout(Form.widget1)
        Form.siteVL.setSpacing(0)
        Form.siteVL.setContentsMargins(0, 0, 0, 0)
        Form.siteVL.setContentsMargins(0, 0, 0, 0)
        Form.siteVL.setObjectName("siteVL")
        Form.siteLE = QtGui.QLineEdit(Form.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.siteLE.sizePolicy().hasHeightForWidth())
        Form.siteLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.siteLE.setFont(font)
        Form.siteLE.setFrame(False)
        Form.siteLE.setEchoMode(QtGui.QLineEdit.Normal)
        Form.siteLE.setCursorPosition(0)
        Form.siteLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.siteLE.setObjectName("siteLE")
        Form.siteVL.addWidget(Form.siteLE)
        Form.siteLbl = QtGui.QLabel(Form.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.siteLbl.sizePolicy().hasHeightForWidth())
        Form.siteLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.siteLbl.setFont(font)
        Form.siteLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.siteLbl.setObjectName("siteLbl")
        Form.siteVL.addWidget(Form.siteLbl)
        Form.horizontalLayout_4.addWidget(Form.widget1)
        Form.widget2 = QtGui.QWidget(Form.trackwayBannerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget2.sizePolicy().hasHeightForWidth())
        Form.widget2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget2.setFont(font)
        Form.widget2.setObjectName("widget2")
        Form.yearVL = QtGui.QVBoxLayout(Form.widget2)
        Form.yearVL.setSpacing(0)
        Form.yearVL.setContentsMargins(0, 0, 0, 0)
        Form.yearVL.setContentsMargins(0, 0, 0, 0)
        Form.yearVL.setObjectName("yearVL")
        Form.yearLE = QtGui.QLineEdit(Form.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.yearLE.sizePolicy().hasHeightForWidth())
        Form.yearLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.yearLE.setFont(font)
        Form.yearLE.setFrame(False)
        Form.yearLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.yearLE.setObjectName("yearLE")
        Form.yearVL.addWidget(Form.yearLE)
        Form.yearLbl = QtGui.QLabel(Form.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.yearLbl.sizePolicy().hasHeightForWidth())
        Form.yearLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.yearLbl.setFont(font)
        Form.yearLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.yearLbl.setObjectName("yearLbl")
        Form.yearVL.addWidget(Form.yearLbl)
        Form.horizontalLayout_4.addWidget(Form.widget2)
        Form.widget3 = QtGui.QWidget(Form.trackwayBannerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget3.sizePolicy().hasHeightForWidth())
        Form.widget3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget3.setFont(font)
        Form.widget3.setObjectName("widget3")
        Form.sectorVL = QtGui.QVBoxLayout(Form.widget3)
        Form.sectorVL.setSpacing(0)
        Form.sectorVL.setContentsMargins(0, 0, 0, 0)
        Form.sectorVL.setContentsMargins(0, 0, 0, 0)
        Form.sectorVL.setObjectName("sectorVL")
        Form.sectorLE = QtGui.QLineEdit(Form.widget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sectorLE.sizePolicy().hasHeightForWidth())
        Form.sectorLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.sectorLE.setFont(font)
        Form.sectorLE.setFrame(False)
        Form.sectorLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.sectorLE.setObjectName("sectorLE")
        Form.sectorVL.addWidget(Form.sectorLE)
        Form.sectorLbl = QtGui.QLabel(Form.widget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sectorLbl.sizePolicy().hasHeightForWidth())
        Form.sectorLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.sectorLbl.setFont(font)
        Form.sectorLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.sectorLbl.setObjectName("sectorLbl")
        Form.sectorVL.addWidget(Form.sectorLbl)
        Form.horizontalLayout_4.addWidget(Form.widget3)
        Form.widget4 = QtGui.QWidget(Form.trackwayBannerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget4.sizePolicy().hasHeightForWidth())
        Form.widget4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget4.setFont(font)
        Form.widget4.setObjectName("widget4")
        Form.levelVL = QtGui.QVBoxLayout(Form.widget4)
        Form.levelVL.setSpacing(0)
        Form.levelVL.setContentsMargins(0, 0, 0, 0)
        Form.levelVL.setContentsMargins(0, 0, 0, 0)
        Form.levelVL.setObjectName("levelVL")
        Form.levelLE = QtGui.QLineEdit(Form.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.levelLE.sizePolicy().hasHeightForWidth())
        Form.levelLE.setSizePolicy(sizePolicy)
        Form.levelLE.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.levelLE.setFont(font)
        Form.levelLE.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.levelLE.setFrame(False)
        Form.levelLE.setCursorPosition(0)
        Form.levelLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.levelLE.setObjectName("levelLE")
        Form.levelVL.addWidget(Form.levelLE)
        Form.levelLbl = QtGui.QLabel(Form.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.levelLbl.sizePolicy().hasHeightForWidth())
        Form.levelLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.levelLbl.setFont(font)
        Form.levelLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.levelLbl.setObjectName("levelLbl")
        Form.levelVL.addWidget(Form.levelLbl)
        Form.horizontalLayout_4.addWidget(Form.widget4)
        Form.trackwayWidget = QtGui.QWidget(Form.trackwayBannerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackwayWidget.sizePolicy().hasHeightForWidth())
        Form.trackwayWidget.setSizePolicy(sizePolicy)
        Form.trackwayWidget.setObjectName("trackwayWidget")
        Form.verticalLayout_10 = QtGui.QVBoxLayout(Form.trackwayWidget)
        Form.verticalLayout_10.setSpacing(0)
        Form.verticalLayout_10.setContentsMargins(0, 0, 12, 0)
        Form.verticalLayout_10.setObjectName("verticalLayout_10")
        Form.trackwayValuesWidget = QtGui.QWidget(Form.trackwayWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackwayValuesWidget.sizePolicy().hasHeightForWidth())
        Form.trackwayValuesWidget.setSizePolicy(sizePolicy)
        Form.trackwayValuesWidget.setObjectName("trackwayValuesWidget")
        Form.horizontalLayout_2 = QtGui.QHBoxLayout(Form.trackwayValuesWidget)
        Form.horizontalLayout_2.setSpacing(0)
        Form.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_2.setObjectName("horizontalLayout_2")
        Form.trackwayTypeLE = QtGui.QLineEdit(Form.trackwayValuesWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackwayTypeLE.sizePolicy().hasHeightForWidth())
        Form.trackwayTypeLE.setSizePolicy(sizePolicy)
        Form.trackwayTypeLE.setBaseSize(QtCore.QSize(0, 3))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.trackwayTypeLE.setFont(font)
        Form.trackwayTypeLE.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.trackwayTypeLE.setFrame(False)
        Form.trackwayTypeLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.trackwayTypeLE.setObjectName("trackwayTypeLE")
        Form.horizontalLayout_2.addWidget(Form.trackwayTypeLE)
        Form.trackwayNumberLE = QtGui.QLineEdit(Form.trackwayValuesWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackwayNumberLE.sizePolicy().hasHeightForWidth())
        Form.trackwayNumberLE.setSizePolicy(sizePolicy)
        Form.trackwayNumberLE.setBaseSize(QtCore.QSize(0, 3))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.trackwayNumberLE.setFont(font)
        Form.trackwayNumberLE.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.trackwayNumberLE.setFrame(False)
        Form.trackwayNumberLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.trackwayNumberLE.setObjectName("trackwayNumberLE")
        Form.horizontalLayout_2.addWidget(Form.trackwayNumberLE)
        Form.horizontalLayout_2.setStretch(0, 1)
        Form.horizontalLayout_2.setStretch(1, 3)
        Form.verticalLayout_10.addWidget(Form.trackwayValuesWidget)
        Form.trackwayLbl = QtGui.QLabel(Form.trackwayWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackwayLbl.sizePolicy().hasHeightForWidth())
        Form.trackwayLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.trackwayLbl.setFont(font)
        Form.trackwayLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.trackwayLbl.setObjectName("trackwayLbl")
        Form.verticalLayout_10.addWidget(Form.trackwayLbl)
        Form.horizontalLayout_4.addWidget(Form.trackwayWidget)
        Form.refreshBtn = QtGui.QPushButton(Form.trackwayBannerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.refreshBtn.sizePolicy().hasHeightForWidth())
        Form.refreshBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.refreshBtn.setFont(font)
        Form.refreshBtn.setCheckable(False)
        Form.refreshBtn.setObjectName("refreshBtn")
        Form.horizontalLayout_4.addWidget(Form.refreshBtn)
        Form.horizontalLayout_4.setStretch(0, 2)
        Form.horizontalLayout_4.setStretch(1, 2)
        Form.horizontalLayout_4.setStretch(2, 2)
        Form.horizontalLayout_4.setStretch(3, 2)
        Form.horizontalLayout_4.setStretch(4, 2)
        Form.horizontalLayout_4.setStretch(5, 1)
        Form.horizontalLayout_4.setStretch(6, 2)
        Form.verticalLayout_14.addWidget(Form.trackwayBannerWidget)
        Form.tabWidget = QtGui.QTabWidget(Form.topBannerWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.tabWidget.setFont(font)
        Form.tabWidget.setObjectName("tabWidget")
        Form.trackEditorTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackEditorTab.sizePolicy().hasHeightForWidth())
        Form.trackEditorTab.setSizePolicy(sizePolicy)
        Form.trackEditorTab.setCursor(QtCore.Qt.ArrowCursor)
        Form.trackEditorTab.setObjectName("trackEditorTab")
        Form.verticalLayout_21 = QtGui.QVBoxLayout(Form.trackEditorTab)
        Form.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_21.setObjectName("verticalLayout_21")
        Form.parametersWidget = QtGui.QWidget(Form.trackEditorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.parametersWidget.sizePolicy().hasHeightForWidth())
        Form.parametersWidget.setSizePolicy(sizePolicy)
        Form.parametersWidget.setObjectName("parametersWidget")
        Form.horizontalLayout_15 = QtGui.QHBoxLayout(Form.parametersWidget)
        Form.horizontalLayout_15.setContentsMargins(12, 0, 12, 0)
        Form.horizontalLayout_15.setObjectName("horizontalLayout_15")
        Form.widget_19 = QtGui.QWidget(Form.parametersWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_19.sizePolicy().hasHeightForWidth())
        Form.widget_19.setSizePolicy(sizePolicy)
        Form.widget_19.setMouseTracking(True)
        Form.widget_19.setObjectName("widget_19")
        Form.verticalLayout_2 = QtGui.QVBoxLayout(Form.widget_19)
        Form.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_2.setObjectName("verticalLayout_2")
        Form.horizontalWidget = QtGui.QWidget(Form.widget_19)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.horizontalWidget.sizePolicy().hasHeightForWidth())
        Form.horizontalWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.horizontalWidget.setFont(font)
        Form.horizontalWidget.setObjectName("horizontalWidget")
        Form.horizontalLayout_12 = QtGui.QHBoxLayout(Form.horizontalWidget)
        Form.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_12.setObjectName("horizontalLayout_12")
        Form.xCoordinateLbl = QtGui.QLabel(Form.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.xCoordinateLbl.sizePolicy().hasHeightForWidth())
        Form.xCoordinateLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.xCoordinateLbl.setFont(font)
        Form.xCoordinateLbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.xCoordinateLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.xCoordinateLbl.setObjectName("xCoordinateLbl")
        Form.horizontalLayout_12.addWidget(Form.xCoordinateLbl)
        Form.xLE = QtGui.QLineEdit(Form.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.xLE.sizePolicy().hasHeightForWidth())
        Form.xLE.setSizePolicy(sizePolicy)
        Form.xLE.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.xLE.setFont(font)
        Form.xLE.setFocusPolicy(QtCore.Qt.WheelFocus)
        Form.xLE.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        Form.xLE.setMaxLength(32759)
        Form.xLE.setFrame(True)
        Form.xLE.setCursorPosition(0)
        Form.xLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.xLE.setObjectName("xLE")
        Form.horizontalLayout_12.addWidget(Form.xLE)
        Form.verticalLayout_2.addWidget(Form.horizontalWidget)
        Form.widget_18 = QtGui.QWidget(Form.widget_19)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_18.sizePolicy().hasHeightForWidth())
        Form.widget_18.setSizePolicy(sizePolicy)
        Form.widget_18.setObjectName("widget_18")
        Form.horizontalLayout_9 = QtGui.QHBoxLayout(Form.widget_18)
        Form.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_9.setObjectName("horizontalLayout_9")
        Form.zCoordinateLbl = QtGui.QLabel(Form.widget_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.zCoordinateLbl.sizePolicy().hasHeightForWidth())
        Form.zCoordinateLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.zCoordinateLbl.setFont(font)
        Form.zCoordinateLbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.zCoordinateLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.zCoordinateLbl.setObjectName("zCoordinateLbl")
        Form.horizontalLayout_9.addWidget(Form.zCoordinateLbl)
        Form.zLE = QtGui.QLineEdit(Form.widget_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.zLE.sizePolicy().hasHeightForWidth())
        Form.zLE.setSizePolicy(sizePolicy)
        Form.zLE.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.zLE.setFont(font)
        Form.zLE.setFocusPolicy(QtCore.Qt.WheelFocus)
        Form.zLE.setFrame(True)
        Form.zLE.setCursorPosition(0)
        Form.zLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.zLE.setObjectName("zLE")
        Form.horizontalLayout_9.addWidget(Form.zLE)
        Form.verticalLayout_2.addWidget(Form.widget_18)
        Form.verticalLayout_2.setStretch(0, 1)
        Form.verticalLayout_2.setStretch(1, 1)
        Form.horizontalLayout_15.addWidget(Form.widget_19)
        Form.widget_21 = QtGui.QWidget(Form.parametersWidget)
        Form.widget_21.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_21.sizePolicy().hasHeightForWidth())
        Form.widget_21.setSizePolicy(sizePolicy)
        Form.widget_21.setObjectName("widget_21")
        Form.verticalLayout_3 = QtGui.QVBoxLayout(Form.widget_21)
        Form.verticalLayout_3.setSpacing(-1)
        Form.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_3.setObjectName("verticalLayout_3")
        Form.rotationWidget = QtGui.QWidget(Form.widget_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.rotationWidget.sizePolicy().hasHeightForWidth())
        Form.rotationWidget.setSizePolicy(sizePolicy)
        Form.rotationWidget.setObjectName("rotationWidget")
        Form.horizontalLayout_3 = QtGui.QHBoxLayout(Form.rotationWidget)
        Form.horizontalLayout_3.setSpacing(0)
        Form.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_3.setObjectName("horizontalLayout_3")
        Form.rotationLbl = QtGui.QLabel(Form.rotationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.rotationLbl.sizePolicy().hasHeightForWidth())
        Form.rotationLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.rotationLbl.setFont(font)
        Form.rotationLbl.setMouseTracking(False)
        Form.rotationLbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.rotationLbl.setAcceptDrops(False)
        Form.rotationLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.rotationLbl.setMargin(0)
        Form.rotationLbl.setObjectName("rotationLbl")
        Form.horizontalLayout_3.addWidget(Form.rotationLbl)
        Form.rotationLE = QtGui.QLineEdit(Form.rotationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.rotationLE.sizePolicy().hasHeightForWidth())
        Form.rotationLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.rotationLE.setFont(font)
        Form.rotationLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.rotationLE.setObjectName("rotationLE")
        Form.horizontalLayout_3.addWidget(Form.rotationLE)
        Form.rotationUncertaintyLE = QtGui.QLineEdit(Form.rotationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.rotationUncertaintyLE.sizePolicy().hasHeightForWidth())
        Form.rotationUncertaintyLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.rotationUncertaintyLE.setFont(font)
        Form.rotationUncertaintyLE.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.rotationUncertaintyLE.setFrame(True)
        Form.rotationUncertaintyLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.rotationUncertaintyLE.setObjectName("rotationUncertaintyLE")
        Form.horizontalLayout_3.addWidget(Form.rotationUncertaintyLE)
        Form.horizontalLayout_3.setStretch(0, 2)
        Form.horizontalLayout_3.setStretch(1, 3)
        Form.horizontalLayout_3.setStretch(2, 2)
        Form.verticalLayout_3.addWidget(Form.rotationWidget)
        Form.depthWidget = QtGui.QWidget(Form.widget_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.depthWidget.sizePolicy().hasHeightForWidth())
        Form.depthWidget.setSizePolicy(sizePolicy)
        Form.depthWidget.setMouseTracking(False)
        Form.depthWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.depthWidget.setAcceptDrops(False)
        Form.depthWidget.setObjectName("depthWidget")
        Form.horizontalLayout_14 = QtGui.QHBoxLayout(Form.depthWidget)
        Form.horizontalLayout_14.setSpacing(0)
        Form.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_14.setObjectName("horizontalLayout_14")
        Form.depthLbl = QtGui.QLabel(Form.depthWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.depthLbl.sizePolicy().hasHeightForWidth())
        Form.depthLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.depthLbl.setFont(font)
        Form.depthLbl.setMouseTracking(False)
        Form.depthLbl.setAcceptDrops(False)
        Form.depthLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.depthLbl.setObjectName("depthLbl")
        Form.horizontalLayout_14.addWidget(Form.depthLbl)
        Form.depthMeasuredLE = QtGui.QLineEdit(Form.depthWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.depthMeasuredLE.sizePolicy().hasHeightForWidth())
        Form.depthMeasuredLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.depthMeasuredLE.setFont(font)
        Form.depthMeasuredLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.depthMeasuredLE.setObjectName("depthMeasuredLE")
        Form.horizontalLayout_14.addWidget(Form.depthMeasuredLE)
        Form.depthUncertaintyLE = QtGui.QLineEdit(Form.depthWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.depthUncertaintyLE.sizePolicy().hasHeightForWidth())
        Form.depthUncertaintyLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.depthUncertaintyLE.setFont(font)
        Form.depthUncertaintyLE.setFrame(True)
        Form.depthUncertaintyLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.depthUncertaintyLE.setObjectName("depthUncertaintyLE")
        Form.horizontalLayout_14.addWidget(Form.depthUncertaintyLE)
        Form.horizontalLayout_14.setStretch(0, 2)
        Form.horizontalLayout_14.setStretch(1, 3)
        Form.horizontalLayout_14.setStretch(2, 2)
        Form.verticalLayout_3.addWidget(Form.depthWidget)
        Form.horizontalLayout_15.addWidget(Form.widget_21)
        Form.dimensionsWidget = QtGui.QWidget(Form.parametersWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.dimensionsWidget.sizePolicy().hasHeightForWidth())
        Form.dimensionsWidget.setSizePolicy(sizePolicy)
        Form.dimensionsWidget.setObjectName("dimensionsWidget")
        Form.verticalLayout_6 = QtGui.QVBoxLayout(Form.dimensionsWidget)
        Form.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_6.setObjectName("verticalLayout_6")
        Form.widthWIdget = QtGui.QWidget(Form.dimensionsWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widthWIdget.sizePolicy().hasHeightForWidth())
        Form.widthWIdget.setSizePolicy(sizePolicy)
        Form.widthWIdget.setObjectName("widthWIdget")
        Form.horizontalLayout_8 = QtGui.QHBoxLayout(Form.widthWIdget)
        Form.horizontalLayout_8.setSpacing(0)
        Form.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_8.setObjectName("horizontalLayout_8")
        Form.widthLbl = QtGui.QLabel(Form.widthWIdget)
        Form.widthLbl.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widthLbl.sizePolicy().hasHeightForWidth())
        Form.widthLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widthLbl.setFont(font)
        Form.widthLbl.setCursor(QtCore.Qt.ArrowCursor)
        Form.widthLbl.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.widthLbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.widthLbl.setLineWidth(-1)
        Form.widthLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.widthLbl.setObjectName("widthLbl")
        Form.horizontalLayout_8.addWidget(Form.widthLbl)
        Form.widthLE = QtGui.QLineEdit(Form.widthWIdget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widthLE.sizePolicy().hasHeightForWidth())
        Form.widthLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widthLE.setFont(font)
        Form.widthLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.widthLE.setObjectName("widthLE")
        Form.horizontalLayout_8.addWidget(Form.widthLE)
        Form.widthMeasuredLE = QtGui.QLineEdit(Form.widthWIdget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widthMeasuredLE.sizePolicy().hasHeightForWidth())
        Form.widthMeasuredLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widthMeasuredLE.setFont(font)
        Form.widthMeasuredLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.widthMeasuredLE.setObjectName("widthMeasuredLE")
        Form.horizontalLayout_8.addWidget(Form.widthMeasuredLE)
        Form.widthUncertaintyLE = QtGui.QLineEdit(Form.widthWIdget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widthUncertaintyLE.sizePolicy().hasHeightForWidth())
        Form.widthUncertaintyLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widthUncertaintyLE.setFont(font)
        Form.widthUncertaintyLE.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        Form.widthUncertaintyLE.setFrame(True)
        Form.widthUncertaintyLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.widthUncertaintyLE.setObjectName("widthUncertaintyLE")
        Form.horizontalLayout_8.addWidget(Form.widthUncertaintyLE)
        Form.horizontalLayout_8.setStretch(0, 1)
        Form.horizontalLayout_8.setStretch(1, 2)
        Form.horizontalLayout_8.setStretch(2, 2)
        Form.horizontalLayout_8.setStretch(3, 1)
        Form.verticalLayout_6.addWidget(Form.widthWIdget)
        Form.lengthWidget = QtGui.QWidget(Form.dimensionsWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.lengthWidget.sizePolicy().hasHeightForWidth())
        Form.lengthWidget.setSizePolicy(sizePolicy)
        Form.lengthWidget.setObjectName("lengthWidget")
        Form.horizontalLayout_13 = QtGui.QHBoxLayout(Form.lengthWidget)
        Form.horizontalLayout_13.setSpacing(0)
        Form.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_13.setObjectName("horizontalLayout_13")
        Form.lengthLbl = QtGui.QLabel(Form.lengthWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.lengthLbl.sizePolicy().hasHeightForWidth())
        Form.lengthLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.lengthLbl.setFont(font)
        Form.lengthLbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.lengthLbl.setLineWidth(-1)
        Form.lengthLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.lengthLbl.setObjectName("lengthLbl")
        Form.horizontalLayout_13.addWidget(Form.lengthLbl)
        Form.lengthLE = QtGui.QLineEdit(Form.lengthWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.lengthLE.sizePolicy().hasHeightForWidth())
        Form.lengthLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.lengthLE.setFont(font)
        Form.lengthLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.lengthLE.setObjectName("lengthLE")
        Form.horizontalLayout_13.addWidget(Form.lengthLE)
        Form.lengthMeasuredLE = QtGui.QLineEdit(Form.lengthWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.lengthMeasuredLE.sizePolicy().hasHeightForWidth())
        Form.lengthMeasuredLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.lengthMeasuredLE.setFont(font)
        Form.lengthMeasuredLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.lengthMeasuredLE.setObjectName("lengthMeasuredLE")
        Form.horizontalLayout_13.addWidget(Form.lengthMeasuredLE)
        Form.lengthUncertaintyLE = QtGui.QLineEdit(Form.lengthWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.lengthUncertaintyLE.sizePolicy().hasHeightForWidth())
        Form.lengthUncertaintyLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.lengthUncertaintyLE.setFont(font)
        Form.lengthUncertaintyLE.setFrame(True)
        Form.lengthUncertaintyLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.lengthUncertaintyLE.setObjectName("lengthUncertaintyLE")
        Form.horizontalLayout_13.addWidget(Form.lengthUncertaintyLE)
        Form.horizontalLayout_13.setStretch(0, 1)
        Form.horizontalLayout_13.setStretch(1, 2)
        Form.horizontalLayout_13.setStretch(2, 2)
        Form.horizontalLayout_13.setStretch(3, 1)
        Form.verticalLayout_6.addWidget(Form.lengthWidget)
        Form.horizontalLayout_15.addWidget(Form.dimensionsWidget)
        Form.widget_11 = QtGui.QWidget(Form.parametersWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_11.sizePolicy().hasHeightForWidth())
        Form.widget_11.setSizePolicy(sizePolicy)
        Form.widget_11.setObjectName("widget_11")
        Form.verticalLayout_11 = QtGui.QVBoxLayout(Form.widget_11)
        Form.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_11.setObjectName("verticalLayout_11")
        Form.widget_2 = QtGui.QWidget(Form.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_2.sizePolicy().hasHeightForWidth())
        Form.widget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget_2.setFont(font)
        Form.widget_2.setObjectName("widget_2")
        Form.horizontalLayout = QtGui.QHBoxLayout(Form.widget_2)
        Form.horizontalLayout.setSpacing(-1)
        Form.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout.setObjectName("horizontalLayout")
        Form.indexLbl = QtGui.QLabel(Form.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.indexLbl.sizePolicy().hasHeightForWidth())
        Form.indexLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.indexLbl.setFont(font)
        Form.indexLbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.indexLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.indexLbl.setObjectName("indexLbl")
        Form.horizontalLayout.addWidget(Form.indexLbl)
        Form.indexLE = QtGui.QLineEdit(Form.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.indexLE.sizePolicy().hasHeightForWidth())
        Form.indexLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.indexLE.setFont(font)
        Form.indexLE.setFrame(True)
        Form.indexLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.indexLE.setObjectName("indexLE")
        Form.horizontalLayout.addWidget(Form.indexLE)
        Form.horizontalLayout.setStretch(0, 1)
        Form.horizontalLayout.setStretch(1, 5)
        Form.verticalLayout_11.addWidget(Form.widget_2)
        Form.widget_10 = QtGui.QWidget(Form.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_10.sizePolicy().hasHeightForWidth())
        Form.widget_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget_10.setFont(font)
        Form.widget_10.setObjectName("widget_10")
        Form.horizontalLayout_5 = QtGui.QHBoxLayout(Form.widget_10)
        Form.horizontalLayout_5.setSpacing(-1)
        Form.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_5.setObjectName("horizontalLayout_5")
        Form.idLbl = QtGui.QLabel(Form.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.idLbl.sizePolicy().hasHeightForWidth())
        Form.idLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.idLbl.setFont(font)
        Form.idLbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.idLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.idLbl.setObjectName("idLbl")
        Form.horizontalLayout_5.addWidget(Form.idLbl)
        Form.idLE = QtGui.QLineEdit(Form.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.idLE.sizePolicy().hasHeightForWidth())
        Form.idLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.idLE.setFont(font)
        Form.idLE.setFrame(True)
        Form.idLE.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        Form.idLE.setObjectName("idLE")
        Form.horizontalLayout_5.addWidget(Form.idLE)
        Form.horizontalLayout_5.setStretch(0, 1)
        Form.horizontalLayout_5.setStretch(1, 5)
        Form.verticalLayout_11.addWidget(Form.widget_10)
        Form.horizontalLayout_15.addWidget(Form.widget_11)
        Form.horizontalLayout_15.setStretch(0, 1)
        Form.horizontalLayout_15.setStretch(1, 2)
        Form.horizontalLayout_15.setStretch(2, 3)
        Form.horizontalLayout_15.setStretch(3, 1)
        Form.verticalLayout_21.addWidget(Form.parametersWidget)
        Form.widget_3 = QtGui.QWidget(Form.trackEditorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_3.sizePolicy().hasHeightForWidth())
        Form.widget_3.setSizePolicy(sizePolicy)
        Form.widget_3.setObjectName("widget_3")
        Form.horizontalLayout_6 = QtGui.QHBoxLayout(Form.widget_3)
        Form.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        Form.horizontalLayout_6.setContentsMargins(-1, 0, 12, 0)
        Form.horizontalLayout_6.setObjectName("horizontalLayout_6")
        Form.selectionWidget = QtGui.QWidget(Form.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.selectionWidget.sizePolicy().hasHeightForWidth())
        Form.selectionWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.selectionWidget.setFont(font)
        Form.selectionWidget.setObjectName("selectionWidget")
        Form.selectionGL = QtGui.QGridLayout(Form.selectionWidget)
        Form.selectionGL.setContentsMargins(0, 0, 0, 0)
        Form.selectionGL.setContentsMargins(0, 0, 0, 0)
        Form.selectionGL.setHorizontalSpacing(0)
        Form.selectionGL.setObjectName("selectionGL")
        Form.selectPriorBtn = QtGui.QPushButton(Form.selectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.selectPriorBtn.sizePolicy().hasHeightForWidth())
        Form.selectPriorBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.selectPriorBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../../../../Desktop/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.selectPriorBtn.setIcon(icon)
        Form.selectPriorBtn.setObjectName("selectPriorBtn")
        Form.selectionGL.addWidget(Form.selectPriorBtn, 1, 0, 1, 1)
        Form.unlinkBtn = QtGui.QPushButton(Form.selectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.unlinkBtn.sizePolicy().hasHeightForWidth())
        Form.unlinkBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.unlinkBtn.setFont(font)
        Form.unlinkBtn.setObjectName("unlinkBtn")
        Form.selectionGL.addWidget(Form.unlinkBtn, 3, 2, 1, 1)
        Form.selectSeriesBtn = QtGui.QPushButton(Form.selectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.selectSeriesBtn.sizePolicy().hasHeightForWidth())
        Form.selectSeriesBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.selectSeriesBtn.setFont(font)
        Form.selectSeriesBtn.setIcon(icon)
        Form.selectSeriesBtn.setObjectName("selectSeriesBtn")
        Form.selectionGL.addWidget(Form.selectSeriesBtn, 1, 1, 1, 1)
        Form.renameBtn = QtGui.QPushButton(Form.selectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.renameBtn.sizePolicy().hasHeightForWidth())
        Form.renameBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.renameBtn.setFont(font)
        Form.renameBtn.setObjectName("renameBtn")
        Form.selectionGL.addWidget(Form.renameBtn, 1, 3, 1, 1)
        Form.selectLaterBtn = QtGui.QPushButton(Form.selectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.selectLaterBtn.sizePolicy().hasHeightForWidth())
        Form.selectLaterBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.selectLaterBtn.setFont(font)
        Form.selectLaterBtn.setIcon(icon)
        Form.selectLaterBtn.setObjectName("selectLaterBtn")
        Form.selectionGL.addWidget(Form.selectLaterBtn, 3, 0, 1, 1)
        Form.linkBtn = QtGui.QPushButton(Form.selectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.linkBtn.sizePolicy().hasHeightForWidth())
        Form.linkBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.linkBtn.setFont(font)
        Form.linkBtn.setObjectName("linkBtn")
        Form.selectionGL.addWidget(Form.linkBtn, 1, 2, 1, 1)
        Form.setSelectedBtn = QtGui.QPushButton(Form.selectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.setSelectedBtn.sizePolicy().hasHeightForWidth())
        Form.setSelectedBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.setSelectedBtn.setFont(font)
        Form.setSelectedBtn.setObjectName("setSelectedBtn")
        Form.selectionGL.addWidget(Form.setSelectedBtn, 3, 3, 1, 1)
        Form.deleteBtn = QtGui.QPushButton(Form.selectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.deleteBtn.sizePolicy().hasHeightForWidth())
        Form.deleteBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.deleteBtn.setFont(font)
        Form.deleteBtn.setAutoRepeatDelay(286)
        Form.deleteBtn.setObjectName("deleteBtn")
        Form.selectionGL.addWidget(Form.deleteBtn, 3, 1, 1, 1)
        Form.horizontalLayout_6.addWidget(Form.selectionWidget)
        Form.noteTE = QtGui.QTextEdit(Form.widget_3)
        Form.noteTE.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.noteTE.sizePolicy().hasHeightForWidth())
        Form.noteTE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.noteTE.setFont(font)
        Form.noteTE.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.noteTE.setObjectName("noteTE")
        Form.horizontalLayout_6.addWidget(Form.noteTE)
        Form.horizontalLayout_6.setStretch(0, 2)
        Form.horizontalLayout_6.setStretch(1, 1)
        Form.verticalLayout_21.addWidget(Form.widget_3)
        Form.line_3 = QtGui.QFrame(Form.trackEditorTab)
        Form.line_3.setFrameShape(QtGui.QFrame.HLine)
        Form.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        Form.line_3.setObjectName("line_3")
        Form.verticalLayout_21.addWidget(Form.line_3)
        Form.navigationWidget = QtGui.QWidget(Form.trackEditorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.navigationWidget.sizePolicy().hasHeightForWidth())
        Form.navigationWidget.setSizePolicy(sizePolicy)
        Form.navigationWidget.setMinimumSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        Form.navigationWidget.setFont(font)
        Form.navigationWidget.setObjectName("navigationWidget")
        Form.horizontalLayout_10 = QtGui.QHBoxLayout(Form.navigationWidget)
        Form.horizontalLayout_10.setSpacing(0)
        Form.horizontalLayout_10.setContentsMargins(12, 0, 12, 0)
        Form.horizontalLayout_10.setObjectName("horizontalLayout_10")
        Form.widget5 = QtGui.QWidget(Form.navigationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget5.sizePolicy().hasHeightForWidth())
        Form.widget5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget5.setFont(font)
        Form.widget5.setObjectName("widget5")
        Form.verticalLayout_7 = QtGui.QVBoxLayout(Form.widget5)
        Form.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_7.setObjectName("verticalLayout_7")
        Form.firstBtn = QtGui.QPushButton(Form.widget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.firstBtn.sizePolicy().hasHeightForWidth())
        Form.firstBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.firstBtn.setFont(font)
        Form.firstBtn.setAcceptDrops(False)
        Form.firstBtn.setIcon(icon)
        Form.firstBtn.setFlat(False)
        Form.firstBtn.setObjectName("firstBtn")
        Form.verticalLayout_7.addWidget(Form.firstBtn)
        Form.firstTrackLbl = QtGui.QLabel(Form.widget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.firstTrackLbl.sizePolicy().hasHeightForWidth())
        Form.firstTrackLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.firstTrackLbl.setFont(font)
        Form.firstTrackLbl.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.firstTrackLbl.setText("")
        Form.firstTrackLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.firstTrackLbl.setObjectName("firstTrackLbl")
        Form.verticalLayout_7.addWidget(Form.firstTrackLbl)
        Form.horizontalLayout_10.addWidget(Form.widget5)
        Form.widget6 = QtGui.QWidget(Form.navigationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget6.sizePolicy().hasHeightForWidth())
        Form.widget6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget6.setFont(font)
        Form.widget6.setObjectName("widget6")
        Form.verticalLayout_8 = QtGui.QVBoxLayout(Form.widget6)
        Form.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_8.setObjectName("verticalLayout_8")
        Form.prevBtn = QtGui.QPushButton(Form.widget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.prevBtn.sizePolicy().hasHeightForWidth())
        Form.prevBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.prevBtn.setFont(font)
        Form.prevBtn.setAcceptDrops(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../../../../../Desktop/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.prevBtn.setIcon(icon1)
        Form.prevBtn.setFlat(False)
        Form.prevBtn.setObjectName("prevBtn")
        Form.verticalLayout_8.addWidget(Form.prevBtn)
        Form.prevTrackLbl = QtGui.QLabel(Form.widget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.prevTrackLbl.sizePolicy().hasHeightForWidth())
        Form.prevTrackLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.prevTrackLbl.setFont(font)
        Form.prevTrackLbl.setText("")
        Form.prevTrackLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.prevTrackLbl.setObjectName("prevTrackLbl")
        Form.verticalLayout_8.addWidget(Form.prevTrackLbl)
        Form.horizontalLayout_10.addWidget(Form.widget6)
        Form.widget_5 = QtGui.QWidget(Form.navigationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_5.sizePolicy().hasHeightForWidth())
        Form.widget_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget_5.setFont(font)
        Form.widget_5.setObjectName("widget_5")
        Form.verticalLayout = QtGui.QVBoxLayout(Form.widget_5)
        Form.verticalLayout.setSpacing(-1)
        Form.verticalLayout.setContentsMargins(0, 16, 0, 0)
        Form.verticalLayout.setObjectName("verticalLayout")
        Form.trackLbl = QtGui.QLabel(Form.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackLbl.sizePolicy().hasHeightForWidth())
        Form.trackLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.trackLbl.setFont(font)
        Form.trackLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.trackLbl.setObjectName("trackLbl")
        Form.verticalLayout.addWidget(Form.trackLbl)
        Form.widget7 = QtGui.QWidget(Form.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget7.sizePolicy().hasHeightForWidth())
        Form.widget7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget7.setFont(font)
        Form.widget7.setObjectName("widget7")
        Form.trackHL = QtGui.QHBoxLayout(Form.widget7)
        Form.trackHL.setSpacing(0)
        Form.trackHL.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        Form.trackHL.setContentsMargins(0, 4, 0, 0)
        Form.trackHL.setObjectName("trackHL")
        Form.leftLE = QtGui.QLineEdit(Form.widget7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.leftLE.sizePolicy().hasHeightForWidth())
        Form.leftLE.setSizePolicy(sizePolicy)
        Form.leftLE.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        Form.leftLE.setFont(font)
        Form.leftLE.setMouseTracking(False)
        Form.leftLE.setMaxLength(32768)
        Form.leftLE.setFrame(False)
        Form.leftLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.leftLE.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        Form.leftLE.setObjectName("leftLE")
        Form.trackHL.addWidget(Form.leftLE)
        Form.pesLE = QtGui.QLineEdit(Form.widget7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.pesLE.sizePolicy().hasHeightForWidth())
        Form.pesLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        Form.pesLE.setFont(font)
        Form.pesLE.setFrame(False)
        Form.pesLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.pesLE.setObjectName("pesLE")
        Form.trackHL.addWidget(Form.pesLE)
        Form.numberLE = QtGui.QLineEdit(Form.widget7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.numberLE.sizePolicy().hasHeightForWidth())
        Form.numberLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        Form.numberLE.setFont(font)
        Form.numberLE.setFrame(False)
        Form.numberLE.setAlignment(QtCore.Qt.AlignCenter)
        Form.numberLE.setObjectName("numberLE")
        Form.trackHL.addWidget(Form.numberLE)
        Form.trackHL.setStretch(0, 1)
        Form.trackHL.setStretch(1, 1)
        Form.trackHL.setStretch(2, 2)
        Form.verticalLayout.addWidget(Form.widget7)
        Form.verticalLayout.setStretch(0, 1)
        Form.verticalLayout.setStretch(1, 1)
        Form.horizontalLayout_10.addWidget(Form.widget_5)
        Form.widget8 = QtGui.QWidget(Form.navigationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget8.sizePolicy().hasHeightForWidth())
        Form.widget8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget8.setFont(font)
        Form.widget8.setObjectName("widget8")
        Form.verticalLayout_9 = QtGui.QVBoxLayout(Form.widget8)
        Form.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_9.setObjectName("verticalLayout_9")
        Form.nextBtn = QtGui.QPushButton(Form.widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.nextBtn.sizePolicy().hasHeightForWidth())
        Form.nextBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.nextBtn.setFont(font)
        Form.nextBtn.setAcceptDrops(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../../../../../Desktop/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.nextBtn.setIcon(icon2)
        Form.nextBtn.setFlat(False)
        Form.nextBtn.setObjectName("nextBtn")
        Form.verticalLayout_9.addWidget(Form.nextBtn)
        Form.nextTrackLbl = QtGui.QLabel(Form.widget8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.nextTrackLbl.sizePolicy().hasHeightForWidth())
        Form.nextTrackLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.nextTrackLbl.setFont(font)
        Form.nextTrackLbl.setText("")
        Form.nextTrackLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.nextTrackLbl.setObjectName("nextTrackLbl")
        Form.verticalLayout_9.addWidget(Form.nextTrackLbl)
        Form.horizontalLayout_10.addWidget(Form.widget8)
        Form.widget9 = QtGui.QWidget(Form.navigationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget9.sizePolicy().hasHeightForWidth())
        Form.widget9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.widget9.setFont(font)
        Form.widget9.setObjectName("widget9")
        Form.verticalLayout_13 = QtGui.QVBoxLayout(Form.widget9)
        Form.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_13.setObjectName("verticalLayout_13")
        Form.lastBtn = QtGui.QPushButton(Form.widget9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.lastBtn.sizePolicy().hasHeightForWidth())
        Form.lastBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.lastBtn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../../../../../Desktop/end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.lastBtn.setIcon(icon3)
        Form.lastBtn.setFlat(False)
        Form.lastBtn.setObjectName("lastBtn")
        Form.verticalLayout_13.addWidget(Form.lastBtn)
        Form.lastTrackLbl = QtGui.QLabel(Form.widget9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.lastTrackLbl.sizePolicy().hasHeightForWidth())
        Form.lastTrackLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.lastTrackLbl.setFont(font)
        Form.lastTrackLbl.setText("")
        Form.lastTrackLbl.setAlignment(QtCore.Qt.AlignCenter)
        Form.lastTrackLbl.setObjectName("lastTrackLbl")
        Form.verticalLayout_13.addWidget(Form.lastTrackLbl)
        Form.horizontalLayout_10.addWidget(Form.widget9)
        Form.line_4 = QtGui.QFrame(Form.navigationWidget)
        Form.line_4.setFrameShape(QtGui.QFrame.VLine)
        Form.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        Form.line_4.setObjectName("line_4")
        Form.horizontalLayout_10.addWidget(Form.line_4)
        Form.widget_17 = QtGui.QWidget(Form.navigationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_17.sizePolicy().hasHeightForWidth())
        Form.widget_17.setSizePolicy(sizePolicy)
        Form.widget_17.setObjectName("widget_17")
        Form.verticalLayout_5 = QtGui.QVBoxLayout(Form.widget_17)
        Form.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_5.setObjectName("verticalLayout_5")
        Form.horizontalLayout_10.addWidget(Form.widget_17)
        Form.widget_16 = QtGui.QWidget(Form.navigationWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_16.sizePolicy().hasHeightForWidth())
        Form.widget_16.setSizePolicy(sizePolicy)
        Form.widget_16.setObjectName("widget_16")
        Form.verticalLayout_22 = QtGui.QVBoxLayout(Form.widget_16)
        Form.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_22.setObjectName("verticalLayout_22")
        Form.addBtn = QtGui.QPushButton(Form.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.addBtn.sizePolicy().hasHeightForWidth())
        Form.addBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.addBtn.setFont(font)
        Form.addBtn.setObjectName("addBtn")
        Form.verticalLayout_22.addWidget(Form.addBtn)
        Form.findBtn = QtGui.QPushButton(Form.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.findBtn.sizePolicy().hasHeightForWidth())
        Form.findBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        Form.findBtn.setFont(font)
        Form.findBtn.setObjectName("findBtn")
        Form.verticalLayout_22.addWidget(Form.findBtn)
        Form.horizontalLayout_10.addWidget(Form.widget_16)
        Form.horizontalLayout_10.setStretch(0, 1)
        Form.horizontalLayout_10.setStretch(1, 1)
        Form.horizontalLayout_10.setStretch(2, 1)
        Form.horizontalLayout_10.setStretch(3, 1)
        Form.horizontalLayout_10.setStretch(4, 1)
        Form.horizontalLayout_10.setStretch(6, 1)
        Form.verticalLayout_21.addWidget(Form.navigationWidget)
        Form.tabWidget.addTab(Form.trackEditorTab, "")
        Form.trackwayEditorTab = QtGui.QWidget()
        Form.trackwayEditorTab.setEnabled(True)
        Form.trackwayEditorTab.setObjectName("trackwayEditorTab")
        Form.verticalLayout_16 = QtGui.QVBoxLayout(Form.trackwayEditorTab)
        Form.verticalLayout_16.setObjectName("verticalLayout_16")
        Form.widget_8 = QtGui.QWidget(Form.trackwayEditorTab)
        Form.widget_8.setObjectName("widget_8")
        Form.horizontalLayout_11 = QtGui.QHBoxLayout(Form.widget_8)
        Form.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        Form.horizontalLayout_11.setObjectName("horizontalLayout_11")
        Form.controlsWidget = QtGui.QWidget(Form.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.controlsWidget.setFont(font)
        Form.controlsWidget.setObjectName("controlsWidget")
        Form.selectionGL_2 = QtGui.QGridLayout(Form.controlsWidget)
        Form.selectionGL_2.setContentsMargins(0, 0, 0, 0)
        Form.selectionGL_2.setContentsMargins(0, 0, 0, 0)
        Form.selectionGL_2.setObjectName("selectionGL_2")
        Form.horizontalLayout_11.addWidget(Form.controlsWidget)
        spacerItem = QtGui.QSpacerItem(20, 198, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.horizontalLayout_11.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        Form.horizontalLayout_11.addItem(spacerItem1)
        Form.widget_7 = QtGui.QWidget(Form.widget_8)
        Form.widget_7.setObjectName("widget_7")
        Form.verticalLayout_20 = QtGui.QVBoxLayout(Form.widget_7)
        Form.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_20.setObjectName("verticalLayout_20")
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        Form.verticalLayout_20.addItem(spacerItem2)
        Form.widget_13 = QtGui.QWidget(Form.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_13.sizePolicy().hasHeightForWidth())
        Form.widget_13.setSizePolicy(sizePolicy)
        Form.widget_13.setObjectName("widget_13")
        Form.verticalLayout_4 = QtGui.QVBoxLayout(Form.widget_13)
        Form.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_4.setObjectName("verticalLayout_4")
        Form.showAllTrackwaysBtn = QtGui.QPushButton(Form.widget_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.showAllTrackwaysBtn.sizePolicy().hasHeightForWidth())
        Form.showAllTrackwaysBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.showAllTrackwaysBtn.setFont(font)
        Form.showAllTrackwaysBtn.setObjectName("showAllTrackwaysBtn")
        Form.verticalLayout_4.addWidget(Form.showAllTrackwaysBtn)
        Form.hideAllTrackwaysBtn = QtGui.QPushButton(Form.widget_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.hideAllTrackwaysBtn.sizePolicy().hasHeightForWidth())
        Form.hideAllTrackwaysBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.hideAllTrackwaysBtn.setFont(font)
        Form.hideAllTrackwaysBtn.setObjectName("hideAllTrackwaysBtn")
        Form.verticalLayout_4.addWidget(Form.hideAllTrackwaysBtn)
        Form.selectAllTrackwaysBtn = QtGui.QPushButton(Form.widget_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.selectAllTrackwaysBtn.sizePolicy().hasHeightForWidth())
        Form.selectAllTrackwaysBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.selectAllTrackwaysBtn.setFont(font)
        Form.selectAllTrackwaysBtn.setIcon(icon)
        Form.selectAllTrackwaysBtn.setObjectName("selectAllTrackwaysBtn")
        Form.verticalLayout_4.addWidget(Form.selectAllTrackwaysBtn)
        Form.repairBtn = QtGui.QPushButton(Form.widget_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.repairBtn.sizePolicy().hasHeightForWidth())
        Form.repairBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.repairBtn.setFont(font)
        Form.repairBtn.setObjectName("repairBtn")
        Form.verticalLayout_4.addWidget(Form.repairBtn)
        Form.verticalLayout_4.setStretch(0, 1)
        Form.verticalLayout_4.setStretch(1, 1)
        Form.verticalLayout_20.addWidget(Form.widget_13)
        Form.horizontalLayout_11.addWidget(Form.widget_7)
        Form.widget_6 = QtGui.QWidget(Form.widget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.widget_6.sizePolicy().hasHeightForWidth())
        Form.widget_6.setSizePolicy(sizePolicy)
        Form.widget_6.setObjectName("widget_6")
        Form.verticalLayout_19 = QtGui.QVBoxLayout(Form.widget_6)
        Form.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_19.setObjectName("verticalLayout_19")
        Form.trackwayCB = QtGui.QComboBox(Form.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.trackwayCB.sizePolicy().hasHeightForWidth())
        Form.trackwayCB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        Form.trackwayCB.setFont(font)
        Form.trackwayCB.setEditable(False)
        Form.trackwayCB.setMaxVisibleItems(32)
        Form.trackwayCB.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        Form.trackwayCB.setObjectName("trackwayCB")
        Form.verticalLayout_19.addWidget(Form.trackwayCB)
        Form.showTrackwayBtn = QtGui.QPushButton(Form.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.showTrackwayBtn.sizePolicy().hasHeightForWidth())
        Form.showTrackwayBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.showTrackwayBtn.setFont(font)
        Form.showTrackwayBtn.setObjectName("showTrackwayBtn")
        Form.verticalLayout_19.addWidget(Form.showTrackwayBtn)
        Form.hideTrackwayBtn = QtGui.QPushButton(Form.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.hideTrackwayBtn.sizePolicy().hasHeightForWidth())
        Form.hideTrackwayBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.hideTrackwayBtn.setFont(font)
        Form.hideTrackwayBtn.setObjectName("hideTrackwayBtn")
        Form.verticalLayout_19.addWidget(Form.hideTrackwayBtn)
        Form.selectTrackwayBtn = QtGui.QPushButton(Form.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.selectTrackwayBtn.sizePolicy().hasHeightForWidth())
        Form.selectTrackwayBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.selectTrackwayBtn.setFont(font)
        Form.selectTrackwayBtn.setObjectName("selectTrackwayBtn")
        Form.verticalLayout_19.addWidget(Form.selectTrackwayBtn)
        Form.setSelectedTrackwayBtn = QtGui.QPushButton(Form.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.setSelectedTrackwayBtn.sizePolicy().hasHeightForWidth())
        Form.setSelectedTrackwayBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setSelectedTrackwayBtn.setFont(font)
        Form.setSelectedTrackwayBtn.setObjectName("setSelectedTrackwayBtn")
        Form.verticalLayout_19.addWidget(Form.setSelectedTrackwayBtn)
        Form.initBtn = QtGui.QPushButton(Form.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.initBtn.sizePolicy().hasHeightForWidth())
        Form.initBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.initBtn.setFont(font)
        Form.initBtn.setObjectName("initBtn")
        Form.verticalLayout_19.addWidget(Form.initBtn)
        Form.horizontalLayout_11.addWidget(Form.widget_6)
        Form.verticalLayout_16.addWidget(Form.widget_8)
        Form.widget_9 = QtGui.QWidget(Form.trackwayEditorTab)
        Form.widget_9.setObjectName("widget_9")
        Form.verticalLayout_15 = QtGui.QVBoxLayout(Form.widget_9)
        Form.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        Form.verticalLayout_15.setObjectName("verticalLayout_15")
        Form.line_6 = QtGui.QFrame(Form.widget_9)
        Form.line_6.setFrameShape(QtGui.QFrame.HLine)
        Form.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        Form.line_6.setObjectName("line_6")
        Form.verticalLayout_15.addWidget(Form.line_6)
        Form.verticalLayout_16.addWidget(Form.widget_9)
        Form.tabWidget.addTab(Form.trackwayEditorTab, "")
        Form.verticalLayout_14.addWidget(Form.tabWidget)
        Form.verticalLayout_12.addWidget(Form.topBannerWidget)

        self.retranslateUi(Form)
        Form.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(Form.firstBtn, Form.nextBtn)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Trackway Manager", None, QtGui.QApplication.UnicodeUTF8))
        Form.communityLbl.setText(QtGui.QApplication.translate("Form", "Community", None, QtGui.QApplication.UnicodeUTF8))
        Form.siteLbl.setText(QtGui.QApplication.translate("Form", "  Site  ", None, QtGui.QApplication.UnicodeUTF8))
        Form.yearLbl.setText(QtGui.QApplication.translate("Form", "  Year  ", None, QtGui.QApplication.UnicodeUTF8))
        Form.sectorLbl.setText(QtGui.QApplication.translate("Form", "Sector", None, QtGui.QApplication.UnicodeUTF8))
        Form.levelLbl.setText(QtGui.QApplication.translate("Form", "  Level  ", None, QtGui.QApplication.UnicodeUTF8))
        Form.trackwayLbl.setText(QtGui.QApplication.translate("Form", "Trackway", None, QtGui.QApplication.UnicodeUTF8))
        Form.refreshBtn.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        Form.xCoordinateLbl.setText(QtGui.QApplication.translate("Form", "X:", None, QtGui.QApplication.UnicodeUTF8))
        Form.zCoordinateLbl.setText(QtGui.QApplication.translate("Form", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        Form.rotationLbl.setText(QtGui.QApplication.translate("Form", "Rotation:", None, QtGui.QApplication.UnicodeUTF8))
        Form.depthLbl.setText(QtGui.QApplication.translate("Form", "Depth:", None, QtGui.QApplication.UnicodeUTF8))
        Form.widthLbl.setText(QtGui.QApplication.translate("Form", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        Form.lengthLbl.setText(QtGui.QApplication.translate("Form", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        Form.indexLbl.setText(QtGui.QApplication.translate("Form", "Index:", None, QtGui.QApplication.UnicodeUTF8))
        Form.idLbl.setText(QtGui.QApplication.translate("Form", "Id:", None, QtGui.QApplication.UnicodeUTF8))
        Form.selectPriorBtn.setText(QtGui.QApplication.translate("Form", "Select Earlier", None, QtGui.QApplication.UnicodeUTF8))
        Form.unlinkBtn.setText(QtGui.QApplication.translate("Form", "Unlink Selected", None, QtGui.QApplication.UnicodeUTF8))
        Form.selectSeriesBtn.setText(QtGui.QApplication.translate("Form", "Select Series", None, QtGui.QApplication.UnicodeUTF8))
        Form.renameBtn.setText(QtGui.QApplication.translate("Form", "Renumber Selected", None, QtGui.QApplication.UnicodeUTF8))
        Form.selectLaterBtn.setText(QtGui.QApplication.translate("Form", "Select Later", None, QtGui.QApplication.UnicodeUTF8))
        Form.linkBtn.setText(QtGui.QApplication.translate("Form", "Link Selected", None, QtGui.QApplication.UnicodeUTF8))
        Form.setSelectedBtn.setText(QtGui.QApplication.translate("Form", "Set Selected ", None, QtGui.QApplication.UnicodeUTF8))
        Form.deleteBtn.setText(QtGui.QApplication.translate("Form", "Delete Selected", None, QtGui.QApplication.UnicodeUTF8))
        Form.firstBtn.setText(QtGui.QApplication.translate("Form", "First Track", None, QtGui.QApplication.UnicodeUTF8))
        Form.prevBtn.setText(QtGui.QApplication.translate("Form", "Prev Track", None, QtGui.QApplication.UnicodeUTF8))
        Form.trackLbl.setText(QtGui.QApplication.translate("Form", "Current Track", None, QtGui.QApplication.UnicodeUTF8))
        Form.nextBtn.setText(QtGui.QApplication.translate("Form", "Next Track", None, QtGui.QApplication.UnicodeUTF8))
        Form.lastBtn.setText(QtGui.QApplication.translate("Form", "Last Track", None, QtGui.QApplication.UnicodeUTF8))
        Form.addBtn.setText(QtGui.QApplication.translate("Form", "Add Track", None, QtGui.QApplication.UnicodeUTF8))
        Form.findBtn.setText(QtGui.QApplication.translate("Form", "Find Track", None, QtGui.QApplication.UnicodeUTF8))
        Form.tabWidget.setTabText(Form.tabWidget.indexOf(Form.trackEditorTab), QtGui.QApplication.translate("Form", "Edit Track", None, QtGui.QApplication.UnicodeUTF8))
        Form.showAllTrackwaysBtn.setText(QtGui.QApplication.translate("Form", "Show All Trackways", None, QtGui.QApplication.UnicodeUTF8))
        Form.hideAllTrackwaysBtn.setText(QtGui.QApplication.translate("Form", "Hide All Trackways", None, QtGui.QApplication.UnicodeUTF8))
        Form.selectAllTrackwaysBtn.setText(QtGui.QApplication.translate("Form", "Select All Trackways", None, QtGui.QApplication.UnicodeUTF8))
        Form.repairBtn.setText(QtGui.QApplication.translate("Form", "Repair Selected", None, QtGui.QApplication.UnicodeUTF8))
        Form.showTrackwayBtn.setText(QtGui.QApplication.translate("Form", "Show Trackway", None, QtGui.QApplication.UnicodeUTF8))
        Form.hideTrackwayBtn.setText(QtGui.QApplication.translate("Form", "Hide Trackway", None, QtGui.QApplication.UnicodeUTF8))
        Form.selectTrackwayBtn.setText(QtGui.QApplication.translate("Form", "Select Trackway", None, QtGui.QApplication.UnicodeUTF8))
        Form.setSelectedTrackwayBtn.setText(QtGui.QApplication.translate("Form", "Set Selected Trackway", None, QtGui.QApplication.UnicodeUTF8))
        Form.initBtn.setText(QtGui.QApplication.translate("Form", "Initialize New Trackway", None, QtGui.QApplication.UnicodeUTF8))
        Form.tabWidget.setTabText(Form.tabWidget.indexOf(Form.trackwayEditorTab), QtGui.QApplication.translate("Form", "Edit Trackway", None, QtGui.QApplication.UnicodeUTF8))

